apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastapi-app
spec:
  source:
    git:
      uri: https://github.com/hailsha/openshift_fastapi.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: fastapi-app:latest
