apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastapi-app
spec:
  source:
    git:
      uri: https://github.com/hailsha/openshift_fastapi.git  # Your Git repository URL
      ref: main  # The branch you want to use (e.g., main)
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:python:3.12-ubi9  # You can change this to the appropriate version of Python
  output:
    to:
      kind: ImageStreamTag
      name: fastapi-app:latest  # The image tag to store the build output
